### ISSUE TITLE
Constant infra warning message when on testnet

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#503]
When using testnet nodes on Galleon, there is a constant infra status warning message display. We should review and investigate the stability of the testnet environment.

**Comment by vishakh** [comment]
Could you please try again? We have fixed some infra issues so testnet nodes should be more stable now.

**Comment by navi-arneja** [comment]
Tested again using Jakartanet nodes and the same issue persists

**Comment by vishakh** [comment]
We made some back end infra changes and Jakarta nodes seem to work with the wallet without warnings whatsoever.

**Comment by vishakh** [comment]
Resolved
